module.exports = {
    CategoryRepository: require('./CategoryRepository'),
    BrandRepository: require('./BrandRepository'),
    ProductRepository: require('./ProductRepository'),
    OptionRepository: require('./OptionRepository'),
    SkuRepository: require('./SkuRepository'),
    BlogRepository: require('./BlogRepository'),
    CurrencyRepository: require('./CurrencyRepository'),
    CustomerRepository: require('./CustomerRepository'),
    TokenRepository: require('./TokenRepository'),
    ReviewRepository: require('./ReviewRepository'),
    WishListRepository: require('./WishListRepository'),
    PermissionRepository: require('./PermissionRepository'),
    RoleRepository: require('./RoleRepository'),
    UserRepository: require('./UserRepository'),
    CouponRepository: require('./CouponRepository'),
    OrderStatusRepository: require('./OrderStatusRepository'),
    ShippingStatusRepository: require('./OrderStatusRepository'),
    PaymentStatusRepository: require('./PaymentStatusRepository'),
    OrderDetailRepository: require('./OrderDetailRepository'),
    OrderRepository: require('./OrderRepository'),
    BannerRepository: require('./BannerRepository')
}